language: node_js
node_js: '10'
install: npm ci
services: mongodb

jobs:
    include:
        - stage: Pull Request Build and Test
          if: type = pull_request
          script:
              - npm test
              - npm run build

        - stage: Build, Test, and Publish
          if: type = push AND branch = master
          script:
              - npm test
              - npm run build
              - ./scripts/publish.sh

        - stage: Automated Dependency Upgrade
          if: type = cron AND branch = master
          script:
              - ./scripts/update.sh
