language: node_js
node_js: 10

git:
    depth: false
    quiet: true
    submodules: false

services:
    - mongodb

script: npm run test && npm run lint && npm run check-format && npm run build

jobs:
    include:
        - stage: release
		  node_js: 10
          deploy:
              provider: script
              skip_cleanup: true
              script:
                  - npx semantic-release
