language: node_js
node_js: 10

git:
    depth: false
    quiet: true
    submodules: false

if: tag IS blank

env:
    global:
        - MONGODB=4.0.1

before_script:
    - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-${MONGODB}.tgz -O /tmp/mongodb.tgz
    - tar -xvf /tmp/mongodb.tgz
    - mkdir /tmp/data
    - ${PWD}/mongodb-linux-x86_64-${MONGODB}/bin/mongod --dbpath /tmp/data --bind_ip 127.0.0.1 --auth &> /dev/null &

install: npm ci

script: npm run test && npm run lint && npm run check-format && npm run build && cat coverage/lcov.info | coveralls

jobs:
    include:
        - stage: release
          deploy:
              provider: script
              skip_cleanup: true
              script:
                  - npx semantic-release
