language: node_js
node_js: 10
env: MONGODB_VERSION=3.6.x

git:
    depth: false
    quiet: true
    submodules: false

services:
    - mongodb

if: tag IS blank

install: npm ci

script: npm run test && npm run lint && npm run check-format && npm run build && cat coverage/lcov.info | coveralls

jobs:
    include:
        - stage: release
          deploy:
              provider: script
              skip_cleanup: true
              script:
                  - npx semantic-release
