language: node_js
node_js: 10

git:
    depth: false
    quiet: true
    submodules: false

if: tag IS blank

env:
    global:
        - MONGODB=4.0.1

install: npm ci

before_script:
    - wget http://fastdl.mongodb.org/linux/mongodb-linux-x86_64-3.6.6.tgz
    - tar -zxvf mongodb-linux-x86_64-3.6.6.tgz
    - mkdir -p ./data/db/27017
    - ./mongodb-linux-x86_64-3.6.6/bin/mongod --fork --dbpath ./data/db/27017 --syslog --port 27017
    - sleep 15

script: npm run test && npm run lint && npm run check-format && npm run build && cat coverage/lcov.info | coveralls

jobs:
    include:
        - stage: release
          deploy:
              provider: script
              skip_cleanup: true
              script:
                  - npx semantic-release
