version: '3'
services:
    app:
        build: .
        image: app
        restart: always
        ports:
            - 3000:3000
        environment:
            PORT: 3000
            LOG_LEVEL: debug
            MONGO_CONNECTION_STRING: mongodb://mongo:27017/
        networks:
            - network
    mongo:
        image: mongo:3.6
        restart: always
        volumes:
            - mongo:/data/db
        networks:
            - network

volumes:
    mongo:

networks:
    network:
